-- Firefly Blog Database Schema

CREATE TABLE IF NOT EXISTS categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    INDEX idx_category_name (name)
);

CREATE TABLE IF NOT EXISTS tags (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    INDEX idx_tag_name (name)
);

CREATE TABLE IF NOT EXISTS posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    description TEXT,
    content TEXT NOT NULL,
    image VARCHAR(255),
    published_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    category_id INT,
    is_draft TINYINT(1) DEFAULT 0,
    FOREIGN KEY (category_id) REFERENCES categories(id),
    INDEX idx_post_title (title),
    INDEX idx_post_slug (slug)
);

CREATE TABLE IF NOT EXISTS post_tags (
    post_id INT,
    tag_id INT,
    PRIMARY KEY (post_id, tag_id),
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS admins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    INDEX idx_admin_username (username)
);

-- Insert default admin (user: admin, pass: admin123, hashed with PBKDF2)
-- Note: The actual hash should be generated by the app, but here is a placeholder
INSERT INTO admins (username, hashed_password) VALUES ('admin', 'pbkdf2_sha256$600000$your_salt$your_hashed_password') ON DUPLICATE KEY UPDATE username=username;
